Import Ubuntu Jammy 1:6.2+dfsg-2ubuntu6.5
This is a port from ubuntu/jammy-updates with the addition of two custom
patches:

 - to get rid of unwanted/unmaintained ROMs
 - VNC: allow websocket connections over AF_UNIX sockets

diff --git a/debian/binfmt-install b/debian/binfmt-install
--- a/debian/binfmt-install
+++ b/debian/binfmt-install
@@ -2,7 +2,8 @@
 
 PACKAGE="$1"
 
-fmts="aarch64 alpha arm armeb cris hppa i386 m68k microblaze mips mipsel mipsn32 mipsn32el mips64 mips64el ppc ppc64 ppc64abi32 ppc64le riscv32 riscv64 s390x sh4 sh4eb sparc sparc32plus sparc64 x86_64 xtensa xtensaeb"
+fmts="aarch64 alpha arm armeb cris hexagon hppa i386 m68k microblaze mips mipsel mipsn32 mipsn32el mips64 mips64el ppc ppc64 ppc64le riscv32 riscv64 s390x sh4 sh4eb sparc sparc32plus sparc64 x86_64 xtensa xtensaeb"
+removed_fmts="ppc64abi32"
 
 # linux ELF_OSABI(byte7) can be 0 (traditional,SYSV) or 3 (GNU/LINUX extensions)
 # binfmt registration does not allow a enum, only value&mask.  So we use broader mask
@@ -19,6 +20,8 @@ fmts="aarch64 alpha arm armeb cris hppa i386 m68k microblaze mips mipsel mipsn32
        armeb_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
        cris_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x4c\x00'
         cris_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
+    hexagon_magic='\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xa4\x00'
+     hexagon_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
        hppa_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x0f'
         hppa_mask='\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
        i386_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x03\x00'
@@ -43,8 +46,6 @@ fmts="aarch64 alpha arm armeb cris hppa i386 m68k microblaze mips mipsel mipsn32
          ppc_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
       ppc64_magic='\x7f\x45\x4c\x46\x02\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15'
        ppc64_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
- ppc64abi32_magic='\x7f\x45\x4c\x46\x01\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15'
-  ppc64abi32_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff'
     ppc64le_magic='\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x15\x00'
      ppc64le_mask='\xff\xff\xff\xff\xff\xff\xff\xfc\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\x00'
     riscv32_magic='\x7f\x45\x4c\x46\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\xf3\x00'
@@ -92,37 +93,62 @@ case "$PACKAGE" in
 esac
 
 mkdir -p debian/$PACKAGE/usr/share/binfmts
+mkdir -p debian/$PACKAGE/usr/libexec/qemu-binfmt
 installed_fmts=
 for fmt in $fmts ; do
     eval "case $fmt in $omit) magic= ;; *) magic=\"\$${fmt}_magic\" mask=\"\$${fmt}_mask\" ;; esac"
     [ -z "$magic" ] && continue
     installed_fmts="$installed_fmts $fmt"
+    # use a special name ending with -binfmt-P so qemu-user
+    # knows it is run by kernel binfmt with P (preserve) flag
+    ln -s ../../bin/qemu-$fmt$SUFFIX debian/$PACKAGE/usr/libexec/qemu-binfmt/$fmt-binfmt-P
     cat >>debian/$PACKAGE/usr/share/binfmts/qemu-$fmt <<EOF
 package $PACKAGE
-interpreter /usr/bin/qemu-$fmt$SUFFIX
+interpreter /usr/libexec/qemu-binfmt/$fmt-binfmt-P
 magic $magic
 offset 0
 mask $mask
 credentials yes
 fix_binary $FIX_BINARY
+preserve yes
 EOF
 done
 
-for action in postinst prerm; do
-    case $action in
-      (postinst) do=import;   phase=configure;;
-         (prerm) do=unimport; phase=remove;;
-    esac
-    cat >>debian/$PACKAGE.$action.debhelper <<EOF
-# binfmt support
-# do not touch binfmts inside a (lxc) container
-if ! grep -zqs ^container= /proc/1/environ
-then
-if test "\$1" = $phase && command -v update-binfmts >/dev/null ; then
-    for fmt in $installed_fmts; do
-	update-binfmts --$do qemu-\$fmt
-    done
-fi
-fi
+# generate postinst and prerm fragments
+for action in postinst:configure:import prerm:remove:unimport
+do
+
+    ifs="$IFS"; IFS=:; set $action; IFS="$ifs"
+    cat >>debian/$PACKAGE.$1.debhelper <<EOF
+binfmt_update() {
+  test $2 = "\$1" || return 0
+  command -v update-binfmts >/dev/null || return 0
+  # do not touch binfmts inside a container
+  # should this be done by update-binfmts instead?
+  if command -v systemd-detect-virt >/dev/null; then
+     systemd-detect-virt --quiet --container && return 0
+  fi
+  grep -zqs ^container= /proc/1/environ && return 0
+  for fmt in $installed_fmts; do
+    update-binfmts --$3 qemu-\$fmt
+  done
+}
+binfmt_update "\$1"
 EOF
 done
+# also generate a preinst script to unregister removed fmts if any
+cat >>debian/$PACKAGE.preinst.debhelper <<EOF
+binfmt_update() {
+  test upgrade = "\$1" || return 0
+  dpkg --compare-versions "\$2" le "1:5.2+dfsg-3~" || return 0
+  command -v update-binfmts >/dev/null || return 0
+  for fmt in $removed_fmts; do
+    if [ -f /var/lib/binfmts/qemu-\$fmt ]; then
+      [ -f /usr/bin/qemu-\$fmt$SUFFIX ] ||
+        echo "$PACKAGE.preinst: note: the warning from update-binfmts about missing qemu-\$fmt$SUFFIX is okay" >&2
+      update-binfmts --package $PACKAGE --remove qemu-\$fmt /usr/bin/qemu-\$fmt$SUFFIX
+    fi
+  done
+}
+binfmt_update "\$1" "\$2"
+EOF
